name: Build Code
on: 
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/chcekout@v4
      - name: compile
        run:
          pwd 
          ls
          g++ -std=c++11 negarr.cpp proxy.cpp -o main
          ls
